// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ST10448895_CMCS_PROG.Data;

#nullable disable

namespace ST10448895_CMCS_PROG.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251015191153_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ST10448895_CMCS_PROG.Models.ApprovalModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApprovalNotes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<int?>("CoordinatorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateApproved")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DateVerified")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("VerificationNotes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId")
                        .IsUnique();

                    b.HasIndex("CoordinatorId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Approvals");
                });

            modelBuilder.Entity("ST10448895_CMCS_PROG.Models.ClaimModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("CoordinatorModelId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Document")
                        .HasColumnType("longtext");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HoursWorked")
                        .HasColumnType("int");

                    b.Property<int>("LecturerId")
                        .HasColumnType("int");

                    b.Property<int?>("ManagerModelId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SubmitDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Verified")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatorModelId");

                    b.HasIndex("LecturerId");

                    b.HasIndex("ManagerModelId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("ST10448895_CMCS_PROG.Models.CoordinatorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CoordinatorModel");
                });

            modelBuilder.Entity("ST10448895_CMCS_PROG.Models.LecturerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Lecturers");
                });

            modelBuilder.Entity("ST10448895_CMCS_PROG.Models.ManagerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ManagerModel");
                });

            modelBuilder.Entity("ST10448895_CMCS_PROG.Models.UploadDocumentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClaimId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OriginalFilename")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.ToTable("UploadDocuments");
                });

            modelBuilder.Entity("ST10448895_CMCS_PROG.Models.ApprovalModel", b =>
                {
                    b.HasOne("ST10448895_CMCS_PROG.Models.ClaimModel", "Claim")
                        .WithOne("Approval")
                        .HasForeignKey("ST10448895_CMCS_PROG.Models.ApprovalModel", "ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ST10448895_CMCS_PROG.Models.CoordinatorModel", "Coordinator")
                        .WithMany()
                        .HasForeignKey("CoordinatorId");

                    b.HasOne("ST10448895_CMCS_PROG.Models.ManagerModel", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId");

                    b.Navigation("Claim");

                    b.Navigation("Coordinator");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("ST10448895_CMCS_PROG.Models.ClaimModel", b =>
                {
                    b.HasOne("ST10448895_CMCS_PROG.Models.CoordinatorModel", null)
                        .WithMany("ClaimsToVerify")
                        .HasForeignKey("CoordinatorModelId");

                    b.HasOne("ST10448895_CMCS_PROG.Models.LecturerModel", "Lecturer")
                        .WithMany("Claims")
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ST10448895_CMCS_PROG.Models.ManagerModel", null)
                        .WithMany("ClaimsToApprove")
                        .HasForeignKey("ManagerModelId");

                    b.Navigation("Lecturer");
                });

            modelBuilder.Entity("ST10448895_CMCS_PROG.Models.UploadDocumentModel", b =>
                {
                    b.HasOne("ST10448895_CMCS_PROG.Models.ClaimModel", "Claim")
                        .WithMany("Documents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");
                });

            modelBuilder.Entity("ST10448895_CMCS_PROG.Models.ClaimModel", b =>
                {
                    b.Navigation("Approval");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("ST10448895_CMCS_PROG.Models.CoordinatorModel", b =>
                {
                    b.Navigation("ClaimsToVerify");
                });

            modelBuilder.Entity("ST10448895_CMCS_PROG.Models.LecturerModel", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("ST10448895_CMCS_PROG.Models.ManagerModel", b =>
                {
                    b.Navigation("ClaimsToApprove");
                });
#pragma warning restore 612, 618
        }
    }
}
